/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActHubRouteImport } from './routes/act-hub'
import { Route as ForUniversitiesRouteImport } from './routes/for-universities'
import { Route as MethodRouteImport } from './routes/method'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActHubRoute = ActHubRouteImport.update({
  id: '/act-hub',
  path: '/act-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ForUniversitiesRoute = ForUniversitiesRouteImport.update({
  id: '/for-universities',
  path: '/for-universities',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/act-hub': typeof ActHubRoute
  '/for-universities': typeof ForUniversitiesRoute
  '/method': typeof MethodRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/act-hub': typeof ActHubRoute
  '/for-universities': typeof ForUniversitiesRoute
  '/method': typeof MethodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/act-hub': typeof ActHubRoute
  '/for-universities': typeof ForUniversitiesRoute
  '/method': typeof MethodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/act-hub' | '/for-universities' | '/method'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/act-hub' | '/for-universities' | '/method'
  id: '__root__' | '/' | '/about' | '/act-hub' | '/for-universities' | '/method'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActHubRoute: typeof ActHubRoute
  ForUniversitiesRoute: typeof ForUniversitiesRoute
  MethodRoute: typeof MethodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/act-hub': {
      id: '/act-hub'
      path: '/act-hub'
      fullPath: '/act-hub'
      preLoaderRoute: typeof ActHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-universities': {
      id: '/for-universities'
      path: '/for-universities'
      fullPath: '/for-universities'
      preLoaderRoute: typeof ForUniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActHubRoute: ActHubRoute,
  ForUniversitiesRoute: ForUniversitiesRoute,
  MethodRoute: MethodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
